Minor quality of life changes (capital Energenie, missing semi-colon, package version outputs)
Achronite/mqtt-energenie-ener314rt pull request #42
Opened 2023-08-13 18:58 UTC by webash

Hello! Again, thanks for the great work on this. I'd like to be able to help make it _more awesome_, if you'd be interested in that!

This first pull request contains some very minor suggestions that have helped me so far when setting up my development environment:
- The Energenie name in the HA discovery packets was lower case, which made it feel _lesser_ alongside the other devices in my HA instance that have capitalised brand names 😅
- There was a missing semi-colon; tiny
- This one might be more controversial: Could I suggest we bring through the package version into the app runtime, so that it can be a) used at logging start but also b) in the discovery packages; the `firmware` property that the `sw` discovery property ends up in, is perfectly suited for displaying version numbers

Hope you like this and are interested in further collaboration. I've submitted #41 too that might be even further controversial, so I'll split it into its own for a separate discussion

(apologies for closing the first version of this PR, I accidentally submitted from my develop branch rather than a feature-specific branch and I am new to this so wasn't sure how to repoint it without recreating the PR)

2023-08-14 08:13 UTC, Achronite approved these changes

2023-08-14 08:29 UTC, Achronite requested changes
On looking into this more it looks like there is a `sw_version` device field (https://developers.home-assistant.io/docs/device_registry_index/), please try this (I haven't tried it) and resubmit. something like this:
```
mf: 'Energenie', sw: 'mqtt-ener314rt', sw_version: `${APP_VERSION}` },
```

2023-08-15 20:39 UTC, webash commented
According to this hard to find bit on [this page about discovery messages](https://www.home-assistant.io/integrations/mqtt/#discovery-messages), `sw` already represents `sw_version`... I'm not sure why this isn't on the page you linked!

![image](https://github.com/Achronite/mqtt-energenie-ener314rt/assets/6205899/ac576412-a755-4971-9b4d-bc81f2d93b7a)

2023-08-16 15:14 UTC, Achronite approved these changes
All good

2023-08-16 15:14 UTC, merged